name: Quarto Render and Publish to Pages
on: workflow_dispatch

jobs:
  build-quarto:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:edge
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: APT
        run: |
          apt update
          apt install pdf2svg quarto
          quarto render
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # upload entire directory
          path: './_book/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        
